### ISSUE TITLE
Silver TEAL Bash

### ISSUE THREAD

**Issue by Bhaney44** [ChoiceCoin/TEAL#1]
**Details**
----------------------------
First Prize: 44,000.00 Choice | Silver Badge
Second Prize: 14,000.00 Choice | Bronze Badge
Third Prize: 7,000.00 Choice | Bronze Badge
Deadline: January 14, 7:00PM PT

**Goal**
----------------------------
The goal for this Bash is to create an Algorand Smart Contract with [TEAL](https://developer.algorand.org/docs/get-details/dapps/avm/teal/) that solves any problem you choose. ​For example, write a smart contract that automatically releases 500 Choice from an address at 5:00 PM every day for seven days. Otherwise, the task is open ended to allow creativity, but the following requirements are intended to provide guidance.

**Requirements** 
----------------------------
1. The program must be submitted as a pull request in the TEAL Repo, in the `SilverBash` folder.
2. All files submitted must be aggregated in one folder with the title: `[UserName]_TEAL_Bash`, such as `Bhaney44_TEAL_Bash`.
3. The PR should be titled `[UserName]_Bash`.
4. The pull request for the program must be made before the task Deadline.
5. The program must be run on the Algorand TestNet.
6. Any TestNet Algo or Choice Asset ID may be used in the program.
7. You must provide screenshots or a video link for the program, but a YouTube link is the best.
8. The program should include a ReadMe file with the problem, solution, description, and run steps.
9. As few scripts and files as possible should be used.
10. The program should be written in TEAL.

**Additional Information**
----------------------------
1. Winners will be selected based on clarity, simplicity, functionality, and design.
2. You can learn more about Algorand Smart Contracts at this [LINK](https://developer.algorand.org/docs/get-details/dapps/smart-contracts/).
3. You can learn more about TEAL at this [LINK](https://medium.com/algorand/understanding-algorand-smart-contracts-b9fc743e7a0f).

**Comment by Bhaney44** [comment]
All winners will be selected and announced before January 17th.

**Comment by ChoiceCoin** [comment]
**Winners**
1. @farsh268 
2. @Paella623 
3. @preciousM494 | @isabela-prettier | @MusaAbdulquadri | @Oluwatunmise-olat | @Samuellyworld | @Temitopeishola | @Favor-code | @henryugwuanyi | @Bi-iznillah
